### ISSUE TITLE
Sudden massive lagspike followed by a disconnect to the main menu

### ISSUE THREAD

**Issue by jp1995** [ValveSoftware/Dota-2#1115]
I'm on Linux.

I lose control of my hero, sometimes I can still briefly see it moving to the last issued location, other times I (and everything else) just runs on the spot. This period lasts about 10 seconds. Then I get disconnected to the main menu. I reconnect, and everything is fine again until the next time. 

This happens roughly every 15-20 minutes. No way for me to reproduce.

While this is happening, the following error message is being rapidly spammed in the console:

`Incorrect client cookie in NoSession from sto#265 (162.254.198.103:27027).  Could be spoofed, ignoring.`

System information:
Distro: Arch Linux 4.8.13-1
WM: Openbox
GPU: AMD / Gigabyte HD 7950 3GB @1000MHz, driver 3.0 Mesa 13.0.2

Thanks!

**Comment by gdrewb-valve** [comment]
Has this ever worked properly?  If it used to work properly when did thing stops working properly?  Is your network completely reliable?

**Comment by jp1995** [comment]
Recently I switched from Windows to Linux, but Dota on Linux worked (surprisingly) fine until 7.00 hit.

The network is definitely reliable, I've played dota for like 2000 hours on it. I used to have some ISP issues where DNS broke but ever since that i've been using Google's DNS servers without fail.

**Comment by gdrewb-valve** [comment]
OK, we'll see if we can find out what's going on.  Given the random nature it probably won't be easy to narrow down.

**Comment by jp1995** [comment]
Okay, thanks for taking the time!

**Comment by regs01** [comment]
This is pretty old problem. In 10v10 10 players in average gets disconnected after hero pick. Happens because of excessive and very long reads from the hard drive that freezing the game. The freeze takes longer than network timeout time.  The problem does not appear with SSD. Only with HDDs.

**Comment by tungnk1993** [comment]
Getting same problem in SEA server. Here's the log:
Incorrect client cookie in NoSession from hkg#74 (153.254.86.172:27016).  Could be spoofed, ignoring.

Moved to low-priority.....

**Comment by jp1995** [comment]
@tungnk1993 So you weren't able to reconnect? I can always reconnect, very quickly in fact, just takes a couple of seconds.

**Comment by tungnk1993** [comment]
@jp1995 I can reconnect, but after a few secs I got auto-disconnected again.Have tried restarting steam,laptop,router, changing dns, didn't help

**Comment by regs01** [comment]
If HDD is busy and actively working for other apps, you will disconnect again.

**Comment by cauanh** [comment]
I got the same problem too. and the console message is exactly as above.
Can someone explain ? it's really pissing me off.

**Comment by gdrewb-valve** [comment]
This doesn't appear to be a Mac/Linux issue and the larger team is investigating so there won't be much status here.

**Comment by jp1995** [comment]
@regs01 @gdrewb-valve @triage-valve
So, I've done some testing.

I installed dota 2 on a SSD and the problem persists. I should point out that the Linux is still installed on a HDD, I just created a new steam library on a separate SSD drive and installed dota there. 

Also, this does not happen in locally hosted games. Only in public games (normal, ranked, private lobby on Luxembourg server for example).

And I've never had this issue on Windows, regardless of drive type. Although this is probably irrelevant.

Hope this is of some help.

**Comment by ghost** [comment]
Were you able to find a solution to this yet? I'm having a similar problem.

**Comment by tungnk1993** [comment]
@trogdor202 the problem disappeared for me automatically, not sure why. It lasted 2 days for me.

**Comment by jp1995** [comment]
@trogdor202 Still occurs, no solution.

**Comment by regs01** [comment]
If you get into 10v10 you'll see how bad it is. 7 to 10 players gets kicked every game after picking a hero.

**Comment by jp1995** [comment]
@regs01 I don't think this is the same issue. 

My disconnects are seemingly random, with high variations in intervals. For example, recently I got disconnected like 3 minutes into the game, but I've also gone 40 minutes without getting a disconnect. The average time remains around 15-20 minutes. Still, it happens at least once every game, but it's not tied to any specific event. I could just be strolling through the jungle with no significant activity on the map, and get disconnected. Or it could happen in the middle of a fight.

You've only mentioned 10v10, specifically a disconnect after picking a hero. I can go into a normal custom (non-local) lobby, disable creeps and be the only hero on the map and still get disconnected. And again, my problem persists on an SSD, with a very high read speed, by the way.

Also, 10v10 is a custom game, and while it is relatively similar to the base game (only adding 10 heroes), that's still potentially adding more faliure points. Especially since 10v10 was last updated well before 7.00

**Comment by regs01** [comment]
Still you disconnects mast likely like other are because of massive swap.

This happens every game
https://yadi.sk/i/ORyiyg5D35wAJ9

**Comment by jp1995** [comment]
Tested on a clean install of Linux Mint, during 112 minutes of game time I did not get a single disconnect.

So this probably means that the issue is somewhere in my Arch system. And I have no idea where to look.

One interesting and glaringly obvious difference is in the Mesa drivers used, Mint currently uses 11.2.0 and Arch is on 13.0.2. However, it's in my mind unlikely that what is seemingly a network issue would be solved by a different graphics driver version, and testing it would be a colossal pain since not only would I have to downgrade Mesa, but also mesa-libgl and therefore all the 32bit libraries in order to simply get steam running.

**Comment by ghost** [comment]
Found this youtube clip related to the same problem I'm having. Problem is, it's in Russian. So shot in the dark that anyone here speaks Russian fluently... But perhaps you'd have better luck than I understanding what they could be referring to.

https://www.youtube.com/watch?v=juO02SAfHE8

**Comment by jp1995** [comment]
Well, I've solved the problem. I'm not entirely sure what the underlying cause is, but it works nevertheless.

@trogdor202 I couldn't understand anything but from context he was going through a bunch of windows network settings. 

So that gave me the idea of checking mine. What I discovered was that I was not using Google's DNS servers as I believed, but rather my ISP's servers. This was due to networkmanager overwriting resolv.conf, where I had manually defined the DNS servers. I fixed that, and using Google's DNS I can play Dota fine. I played two full games (both ~50 minutes) with no disconnects.

The reason I don't really know the underlying cause is that, when I tried to replicate this problem on a clean Linux Mint install, Dota ran fine using my ISP's DNS. Similarly, I switched to my Windows system where I've been playing these past weeks (all on the same computer, only changing drives) and that is also using my ISP's DNS. So this only occurs on my Arch system.

It's very specific and I don't know if this will help anyone else, but if you're having this issue, try to change your DNS servers. If you don't like google, try openDNS or openNIC.

**Comment by ghost** [comment]
@jp1995 Ah, that might make sense. Just yesterday I played at a different location than I normally do and had zero issues with it. Interesting. I'll give that a try. Last night I shut off my cable modem/router and plan on turning it back on this afternoon for an IP change. But i'll definitely give your suggestion a go. I'm thrilled to hear it worked. Thanks so much.

**Comment by jp1995** [comment]
Something something celebrating too early..

Didn't play more on linux until today due to some unrelated issues. Problem occurs again. DNS is not related to the issue. Feeling kind of hopeless right now to be honest. 

@trogdor202 Did this work for you?

**Comment by ghost** [comment]
@jp1995 

Unfortunately i'm still having issues too. Like I mentioned, I played at a different location and had no problems, both on a different pc and also on a laptop that I normally play on that usually has this problem. I contacted my ISP and everything seems fine on their end and my net is fine with everything else I do.

But still having the issue when I play at home. Which is super frustrating.

**Comment by ghost** [comment]
@jp1995 

It couldn't be a possible router problem? I'm currently using a netgear cable modem router that I plug directly into.

**Comment by jp1995** [comment]
@trogdor202 I mean, if it was a router problem then it would be prevalent on any system regardless of OS. The fact that it's working on Mint and Windows 10, and not working on Arch kind of disproves that, at least in my case. 

When I have some time I'll do a fresh arch install and see if it persists there.

**Comment by ghost** [comment]
@jp1995 
I just tested again, played on the same laptop, nothing changed, just a different locale. No problems. Not sure why the difference. I'd like to figure it out though, I'd like to have the freedom to play at home.

**Comment by jp1995** [comment]
@trogdor202 Do you use NetworkManager?

**Comment by ghost** [comment]
@jp1995 
I'm not especially savvy, so I'm not sure.

I will say, I reset my cable modem router, just a hard factory reset, and since haven't had any problems. Occasional lag, but nothing like before, and I open the console when the lag hits and that error message no longer shows.

**Comment by jp1995** [comment]
@trogdor202 
Glad to hear that.

I played this FPS called Insurgency and I noticed a similar lagspike, occuring in a similar frequency. I searched wider, looking for anything that might cause lag spikes in multiplayer games and stumbled upon a reddit thread. Apparently networkmanager can cause such behaviour. I removed networkmanager and the problem appears to have disappeared. 

If your problem returns you might want to try this, although if you use wifi then you can't just remove networkmanager, you'll need to replace it with something else to manage your connections. Wicd is basically the same in functionality, although I've always had problems with it.

I'll leave this issue open for a couple days just in case I've got it wrong again.

**Comment by jp1995** [comment]
Dota works flawlessly! Closing the issue.

**Comment by ghost** [comment]
I don't use networkmanager I don't think, but I'm glad that it worked alright for you!
