### ISSUE TITLE
Linux: hero health bars does not render the graphics correctly

### ISSUE THREAD

**Issue by lynx29** [ValveSoftware/Dota-2#120]
Sometimes when playing the game, I would get this hero health bar graphics.
![2015-06-26_00001](https://cloud.githubusercontent.com/assets/13056543/8388689/c4f0ad20-1c97-11e5-94c1-fe04a9c12683.jpg)
Then opening dashboard menu, I get this graphics image.
![2015-06-26_00002](https://cloud.githubusercontent.com/assets/13056543/8388826/fce058b4-1c99-11e5-8440-5571d38a2d24.jpg)

Steam System Information

Processor Information:
    Vendor:  AuthenticAMD
    CPU Family:  0x15
    CPU Model:  0x13
    CPU Stepping:  0x1
    CPU Type:  0x0
    Speed:  3900 Mhz
    2 logical processors
    2 physical processors
    HyperThreading:  Unsupported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Supported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.0-16-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06

Video Card:
    Driver:  ATI Technologies Inc. AMD Radeon HD 8470D

```
Driver Version:  4.4.13374 Compatibility Profile Context 15.20.1013
OpenGL Version: 4.4
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x1002
DeviceID:  0x9996
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 16.14" x 9.06"  (18.50" diag)
                                        41.0cm x 23.0cm  (47.0cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Realtek ALC887-VD

Memory:
    RAM:  7111 Mb

Miscellaneous:
    UI Language:  English
    LANG:  en_PH.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  461315 Mb
    Largest Free Hard Disk Block:  347180 Mb

**Comment by gdrewb-valve** [comment]
Likely the same graphics problem as the other UI rendering issues, which should get fixed soon.

**Comment by gdrewb-valve** [comment]
Does the 6/26 update help?

**Comment by supereddie** [comment]
After the 6/26 update, I have the dissapearing healthbar problem as well (didn't try to play before). One other thing to note: when opening the console, the heathbars render on top of the console.

>Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x3a
    CPU Stepping:  0x9
    CPU Type:  0x0
    Speed:  3900 Mhz
    8 logical processors
    4 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported
    
>Network Information:
    Network Speed:  
    
>Operating System Version:
    Ubuntu 15.04 (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.19.3-031903-generic
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11701000
    X Window Manager:  Compiz
    Steam Runtime Version:  steam-runtime-release_2015-01-06
    
>Video Card:
    Driver:  X.Org Gallium 0.4 on AMD TAHITI

    Driver Version:  3.0 Mesa 10.7.0-devel (git-316206e 2015-06-26 vivid-oibaf-ppa)
    OpenGL Version: 3.0
    Desktop Color Depth: 24 bits per pixel
    Monitor Refresh Rate: 60 Hz
    VendorID:  0x1002
    DeviceID:  0x6798
    Number of Monitors:  2
    Number of Logical Video Cards:  1
    Primary Display Resolution:  1920 x 1080
    Desktop Resolution: 3840 x 1080
    Primary Display Size: 20,04" x 11,26"  (22,95" diag)
                                            50,9cm x 28,6cm  (58,3cm diag)
    Primary VRAM Not Detected
    
>Sound card:
    Audio device: Realtek ALC898
    
>Memory:
    RAM:  15936 Mb
    
>Miscellaneous:
    UI Language:  English
    LANG:  nl_NL.UTF-8
    Microphone:  Not set
    Total Hard Disk Space Available:  236870 Mb
    Largest Free Hard Disk Block:  106749 Mb

**Comment by gdrewb-valve** [comment]
It's expected for the health bars to be above the console.

**Comment by lynx29** [comment]
after 6/26 update, I could still get that graphics issue.

**Comment by danginsburg** [comment]
Still looking into this here, but it is related to missing fonts.  I resolved it by doing:

```
sudo apt-get install ttf-mscorefonts-installer
sudo fc-cache -f -v
```

Does that resolve the issue for you?

**Comment by presianbg** [comment]
installing ttf-mscorefonts is doing the trick. But Is that really necessary?

**Comment by gdrewb-valve** [comment]
We have another change coming which should fix the underlying issue.

**Comment by weirddan455** [comment]
I found a workaround to this if you don't want to install Microsoft Fonts.  For some reason, Dota has it's won font configuration folder that overrides the system defaults located at steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d.  Sounds pretty silly to me but I guess Valve has their reasons.

Anyway, on Arch at least, the ttf-liberation font package includes a configuration file that aliases Arial to Liberation (located at /etc/fonts/conf.avail/30-ttf-liberation-sans.conf.)  Arial is the font that Dota can't find and messes up your UI.

So, the workaround is to copy that file to the Dota font directory or make a new file there if you don't have it.  Contents of the file:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE fontconfig SYSTEM "../fonts.dtd">
<fontconfig>
         
        <alias binding="same">
          <family>Arial</family>
            <accept>
              <family>Liberation Sans</family>
            </accept>
        </alias>
        <alias binding="same">
          <family>Liberation Sans</family>
            <default>
              <family>Arial</family>
            </default>
        </alias>
</fontconfig>

You can just copy paste that and save it as steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/30-ttf-liberation-sans.conf.  If you don't have Liberation installed, change the two instances of <family> to DejaVu Sans, Droid Sans, or whatever you happen to have installed on your system.

**Comment by presianbg** [comment]
@weirddan455 
Nice found :) Works perfect. 10x

**Comment by weirddan455** [comment]
Actually I think they fixed it in the update that just came through.  I deleted my workaround and everything stays intact.

**Comment by sylware** [comment]
:( I still don't have console font (with your fix or not) I have DejaVu installed though.
If I install arial.ttf in my font directory, the console gets font and heroes get names.
There is something still weird with the fontconfig non-microsoft font fallback configuration.

**Comment by gdrewb-valve** [comment]
@sylware, what fontconfig fonts do you have installed?  fontconfig is always supposed to return a font in its sorted match list so I'm not sure why it would show nothing unless no fonts could be found.

**Comment by sylware** [comment]
I have only the DejaVu ttf and Noto ttf fonts in $HOME/.local/share/fonts

**Comment by gdrewb-valve** [comment]
You have fonts so fontconfig should pick one of them, I'm not sure why it wouldn't.

**Comment by sylware** [comment]
The weird thing: If I drop arial.ttf in my font directory, the console will get a font and heroes will have names (above the health bar in a game).
I tried to removed the fontconfig cache (reborn one), tried to make it work with only dejavu (removed Noto), nothing. Like it really really wants arial.ttf ignoring the fontconfig configuration files.

**Comment by sylware** [comment]
Seems I nailed it: I dropped liberation fonts in my font dir and console/heroes' names are ok.

The reborn fontconfig fallback from arial font is specific to liberation font and does not work with dejavu font.

**Comment by gdrewb-valve** [comment]
Reborn itself isn't doing anything with fontconfig for fallbacks, we simply ask fontconfig for all matches and it's supposed to handle things.  I'm not sure why it would work with Liberation but not Deja Vu, but maybe some font property we're setting is affecting things oddly.  We'll mark this one down for more extensive repro efforts in the future.

**Comment by weirddan455** [comment]
I can confirm this.  If I uninstall ttf-liberation, the console fonts and hitpoints go missing.

The reason is because you're trying to ship your own fontconfig configuration instead of letting the systemwide configuration handle it.

```
cd steamapps/common/dota 2 beta/game/core/panorama
mv fonts fonts-bak
ln -s /etc/fonts fonts
```

Fixes this so it will work with DejaVu fonts.

**Comment by gdrewb-valve** [comment]
The people who set that up supposedly set it up to be non-exclusive but I guess that's not working.  I'll pass this on to them.

**Comment by gdrewb-valve** [comment]
If you change the panorama fonts.conf to include /etc/fonts as a directory does that fix the issue?

**Comment by gdrewb-valve** [comment]
Scratch the fonts.conf suggestion, that isn't going to work.  I heard back and unfortunately it looks like the current setup has a limitation that prevents using the standard system fontconfig.  You should still be able to use fonts in /usr/share/fonts and such or the workaround that you've found.  In the long term the underlying code is going to be switched and this problem will go away but for now it's stuck the way it is.

**Comment by threexone** [comment]
Hi,

I have the same problem as the initial post. I installed ttf-mscorefonts, but the problem is still present.

**My system information** :

Processeur :
    Fabricant : GenuineIntel
    Famille du processeur : 0x6
    Modèle du processeur : 0x3a
    Révision processeur : 0x9
    Type de processeur : 0x0
    Fréquence : 3400 Mhz
    4 processeurs logiques
    4 processeurs physiques
    HyperThreading : Non pris en charge
    FCMOV : Pris en charge
    SSE2 : Pris en charge
    SSE3 : Pris en charge
    SSSE3 : Pris en charge
    SSE4a : Non pris en charge
    SSE41 : Pris en charge
    SSE42 : Pris en charge

Réseau :
    Vitesse du réseau : 

Version du système d'exploitation :
    Linux Mint 17.1 Rebecca (64 bits)
    Nom du noyau : Linux
    Version du noyau : 3.13.0-37-generic
    Éditeur du serveur X : The X.Org Foundation
    Version du serveur X : 11501000
    Gestionnaire de fenêtres X : Mutter (Muffin)
    Version d'exécution Steam : steam-runtime-release_2015-06-12

Carte graphique :
    Pilote : ATI Technologies Inc. AMD Radeon HD 5800 Series 

```
Version du pilote : 4.4.13374 Compatibility Profile Context 13.35.1005
Version OpenGL : 4.4
Profondeur de couleur du bureau : 24 bits par pixel
Taux de rafraîchissement du moniteur : 60 Hz
ID fabricant : 0x1002
ID périphérique : 0x6899
Nombre de moniteurs : 1
Nombre de cartes vidéo logiques : 1
Résolution de l'affichage principal : 1920 x 1080
Résolution du bureau : 1920 x 1080
Taille de l'affichage principal : 20,91" x 11,77" (23,98" diag)
                                        53,1cm x 29,9cm (60,9cm diag)
Mémoire vidéo principale non détecté
```

Carte son :
    Périphérique audio : Realtek ALC892

Mémoire :
    RAM : 7933 Mo

Divers :
    Langue de l'interface : Français
    LANGUE : fr_FR.UTF-8
    Micro : Not set
    Espace disque total disponible : 65578 Mo
    Plus grand bloc disponible sur le disque dur : 18883 Mo

**Comment by threexone** [comment]
A quick update on my case : I installed the new AMD driver (15.9) as indicated in #380 . It completely solved my problem.

**Comment by danginsburg** [comment]
Thanks, closing.
