### ISSUE TITLE
[Mac] Game always asks for network permission

### ISSUE THREAD

**Issue by ssnl** [ValveSoftware/Dota-2#141]
Dota always asks for network permission when started. Source 1 doesn't have this problem.

**Comment by gdrewb-valve** [comment]
What network permission UI do you mean?  Can you screenshot it?

**Comment by SsnL** [comment]
![screenshot 2015-06-27 10 52 40](https://cloud.githubusercontent.com/assets/5674597/8393212/a7ba4838-1cba-11e5-9e1e-96a2de7412cf.png)

**Comment by gdrewb-valve** [comment]
OK, it's the built-in Mac UI, this may be expected.

**Comment by SsnL** [comment]
Yeah, but I only needed to allow once when I first opened the game for source 1. I have to click "allow" every time I open source 2.

**Comment by gdrewb-valve** [comment]
We've found the issue and the next update should fix it.

**Comment by SsnL** [comment]
Thanks

**Comment by gdrewb-valve** [comment]
Is this fixed in the 6/30 update?

**Comment by cesargog** [comment]
Yes, fixed for me. macbook pro late 2011 intel hd 3000

**Comment by gdrewb-valve** [comment]
Thanks, closing.

**Comment by SsnL** [comment]
Confirm fixed.

**Comment by rained23** [comment]
Hi, this still happen to me.

You can reproduce it by hosting a lobby for custom game, it will ask for a permission randomly.

**Comment by gdrewb-valve** [comment]
When hosting a lobby your computer is going to do network operations so it seems normal for the permission dialog to come up then.  Can you explain further why you don't think it should?

**Comment by gdrewb-valve** [comment]
Is it the random nature of the dialog that you're asking about?  Reborn can definitely try to listen for people connecting in to your lobby so that's normal, but why the OS shows the permission dialog randomly is unknown.  Go ahead and open a separate issue for that if I'm understanding you correctly.

**Comment by rained23** [comment]
Yes it is, I have mysql server running and it only ask once for permission to allow it in my firewall,
I think it should only ask once for entire session of Reborn running. Right now its really frustrating, when its pop up randomly while I am for sure giving it permission. I will create an issue for this.
