### ISSUE TITLE
Battlepass update broke Mac dota 2 

### ISSUE THREAD

**Issue by prabh94** [ValveSoftware/Dota-2#1597]
#### Macbook air 2018

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): https://gist.github.com/prabh94/cc8c9ae785eb3d625494e63bce6eb7e2
* Have you checked for system updates?: [Yes/No] Yes
* Are you using the latest stable video driver available for your system? [Yes/No] Yes
* Have you verified the game files?: [Yes/No] Yes

#### Please describe your issue in as much detail as possible:
Game crashes when i open any profile in game, try to watch a match, try to connect to any server.

#### Steps for reproducing this issue:

1. Open Dota 2 in Mac
2. Try to view any person's profile.
3. Try to watch any match from watch tab.
4. Try to connect to any server (normal/ranked/custom games)

**Comment by dinasti11** [comment]
Same problem here, looks like everyone using Mac is having this

**Comment by prabh94** [comment]
https://www.reddit.com/r/DotA2/comments/blxgtq/mac_version_of_dota_2_broken/

everyone is reporting the same. Thanks for looking into it.

**Comment by markcaldropoli** [comment]
The newest update just fixed it! Much appreciated.

**Comment by danginsburg** [comment]
Thanks for the confirmation.  Yes, we believe we have fixed the issue.

**Comment by SwagDad** [comment]
Thank you so much Kisak-Valve.

**Comment by prabh94** [comment]
@danginsburg i can watch games and play games. But my dota 2 crashes when i view ANY profile  (in game)

I provide you with more information if needed

**Comment by elsennov** [comment]
I have updated to the latest version, but still got the crash when starting bot match using Ranked Matchmaking AI.

**Comment by prabh94** [comment]
My problem persists. I can't view ANY player profiles. Instant crash. Please help.

Macbook Air 2018.
using Vulkan and desktop-friendly borderless window mode.
have tried Validating game files, restarting pc and everything possible. No fix.

**Comment by elsennov** [comment]
Updated to the latest version, the problem still persist.
Mac pro, mojave, 15", 2018

**Comment by danginsburg** [comment]
> I provide you with more information if needed

Yes, please open another bug on this.  Also would be helpful to know if this is Vulkan-only or if it happens in GL.  So far I haven't been able to repro it.  

Edit: Actually, I did get it to repro on one of my Macs.  Not happening universally but I do see the crash when looking at user profiles.  Investigating.

**Comment by danginsburg** [comment]
OK, I've reproduced this problem and have a workaround.  It's this issue: https://github.com/KhronosGroup/MoltenVK/issues/594

I'll get an update shipped today, but in the meantime if you want a fix unzip the attached libMoltenVK.dylib over the copy in ~/Library/Application Support/Steam/steamapps/common/dota 2 beta/game/bin/osx64.

[libMoltenVK.dylib.zip](https://github.com/ValveSoftware/Dota-2/files/3157319/libMoltenVK.dylib.zip)

**Comment by prabh94** [comment]
@danginsburg I am able to view profiles now. thanks for the fix. I did re download and install the game too.

If you need anything else, please let me know. Thanks once again!

**Comment by danginsburg** [comment]
@prabh94 Thanks for the confirmation.  The fix will ship with the next update.

**Comment by frncsgelay** [comment]
Still broken on me. Tried to play turbo and game crashes every 2-5mins. I have Macbook Pro 2015 13" Retina.

**Comment by kisak-valve** [comment]
Hello @frncsgelay, that doesn't sound like the issue being tracked in this issue report. Is there a pattern to the crashing you're seeing?

**Comment by danginsburg** [comment]
I'm going to close this issue, new crashes should be opened in another issue.
