### ISSUE TITLE
[Linux] Cannot launch Dota. Unable to load libpangoft2-1.0.so

### ISSUE THREAD

**Issue by mirfan-link** [ValveSoftware/Dota-2#1705]
#### Your system information

* System information from steam 
(https://gist.github.com/mirfan-link/e60cae03143e0045a09948e51556d84f): 
* Have you checked for system updates?: [Yes] 
* Are you using the latest stable video driver available for your system? [Yes]
* Have you verified the game files?: [Yes]

#### Please describe your issue in as much detail as possible:
Game crashes on launch. Get black screen with window "Unable to load libpangoft2-1.0.so, your game install may be corrupted or you may system conflict"

opening dota.sh will shows:
```
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/mirfan/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561198306013571 [API loaded yes]
Steam_SetMinidumpSteamID:  Setting Steam ID:  76561198306013571
Setting breakpad minidump AppID = 373300
INTEL-MESA: warning: Haswell Vulkan support is incomplete
 failed to dlopen "libpangoft2-1.0.so" error=/mnt/9b197ab5-de68-4179-83c4-e1e2ae7adde7/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpangoft2-1.0.so: symbol png_set_expand_gray_1_2_4_to_8 version PNG12_0 not defined in file libpng12.so.0 with link time reference
 failed to dlopen "libpangoft2-1.0.so" error=/mnt/9b197ab5-de68-4179-83c4-e1e2ae7adde7/SteamLibrary/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libpangoft2-1.0.so: symbol png_set_expand_gray_1_2_4_to_8 version PNG12_0 not defined in file libpng12.so.0 with link time reference
```
#### Steps for reproducing this issue:

1. run dota from steam client

**Comment by TTimo** [comment]
Hello @mirfan-link, please provide the complete system information from the Help > System Information dialog. In particular, please wait for the "Steam Linux Runtime Information" section to be filled up and provide that to us, thank you!

**Comment by mirfan-link** [comment]
I have been waiting for the "runtime information tool" report but it takes a very long time and nothing is displayed.

**Comment by TTimo** [comment]
Please make sure you are running the latest Steam beta - the issue you are reporting about the srt-info tool being very slow or unresponsive may still happen in the general release, but should not longer be happening in the beta version.

**Comment by gemakochi** [comment]
i also have this issue.

https://gist.github.com/gemakochi/20e9403cd35ec4774d3c3a3776f740ea
[console.txt](https://github.com/ValveSoftware/Dota-2/files/4334250/console.txt)
[crash.zip](https://github.com/ValveSoftware/Dota-2/files/4334247/crash.zip)

**Comment by kisak-valve** [comment]
Hello @gemakochi, running Dota 2 from outside the Steam runtime is not supported. If you're going to test from outside of Steam, consider using `~/.steam/debian-installation/ubuntu12_32/steam-runtime/run.sh ./dota.sh` to give Dota 2 a similar environment as when it's run from Steam.

**Comment by gemakochi** [comment]
with that command game launched and crushed after logo, no error message displayed other then console.
[console.txt](https://github.com/ValveSoftware/Dota-2/files/4334289/console.txt)

**Comment by TTimo** [comment]
Interesting that `run.sh` doesn't work either, but this is a different error than the pango issue we are tracking: `failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory`.

@gemakochi please run Dota 2 from the Steam client instead and see if the same error reproduces?

**Comment by gemakochi** [comment]
it's same, game crashes after logo. no visible error message. how can i gather logs?

https://youtu.be/DFGyMZyH4dk

**Comment by TTimo** [comment]
You can run steam from the command line to capture logs.

We can ignore the `libtensorflow.so` thing as a red herring - https://github.com/ValveSoftware/Dota-2/issues/1418#issuecomment-373493831

An updated crash dump would be useful. Your latest log https://github.com/ValveSoftware/Dota-2/files/4334289/console.txt doesn't report a libpangoft2 error either so you may be running into something different.

**Comment by gemakochi** [comment]
i used same command from shortcut and it failed again but it's working without %U parameter. what "%U" does?


![2020-03-16 18-46-41 ekran görüntüsü](https://user-images.githubusercontent.com/581848/76775533-887fb100-67b6-11ea-8c7f-971b234d5530.png)

[crash_20200316184339_1.zip](https://github.com/ValveSoftware/Dota-2/files/4338987/crash_20200316184339_1.zip)
[console.txt](https://github.com/ValveSoftware/Dota-2/files/4339003/console.txt)

**Comment by kisak-valve** [comment]
For reference, the attached minidump is a SIGSEGV in libtier0.so coming from libclient.so (part of Dota 2).

**Comment by TTimo** [comment]
It looks like your steam launch script is a distribution or user-altered version of the official steam launch script. I can't help with that but maybe you can bypass this cruft and launch directly by running `~/.steam/steam/steam.sh`

**Comment by gemakochi** [comment]
it's working with that command. ~~i'm not sure if i change that shortcut.~~ it's debian specific.
[console.txt](https://github.com/ValveSoftware/Dota-2/files/4339096/console.txt)

**Comment by TTimo** [comment]
Do you mean Dota 2 is working, e.g. problem fixed?

**Comment by gemakochi** [comment]
yes thank you, it's looks like i don't have a problem at all.

**Comment by smcv** [comment]
@gemakochi If the Debian `/usr/games/steam` script does not work, but running `~/.steam/steam/steam.sh` directly does work, then please report that to Debian (not here) as a bug in the `steam` package. Please describe what you do, what you expected to happen, and what actually happens, including any log output that `steam` or `~/.steam/steam/steam.sh` produces when run from a command-line.

The `%U` syntax in `.desktop` shortcuts gets replaced by a URL like `steam://store`, or removed completely if there is no relevant URL. This happens automatically when launching it from a desktop menu. If you are running Steam from a command-line, don't type `%U`.

**Comment by gemakochi** [comment]
before your comment i was able to launch game with both `/usr/games/steam` and `~/.steam/steam/steam.sh`. game was crashing with `%U` added, last crash dump was about that.

then i edit shortcut, removed `%U`, lauched and joined a ranked game. then i notice key shortcuts was not as i set before. i quit game to change settings. now i can't launch game again. i attached latest crash dump.

[console2.txt](https://github.com/ValveSoftware/Dota-2/files/4339334/console2.txt)
[crash_20200316194207_1.zip](https://github.com/ValveSoftware/Dota-2/files/4339325/crash_20200316194207_1.zip)

**Comment by JackTemaki** [comment]
As the original Issue was never solved, here my explanation (which solved the exact same issue for me):

The `libpangoft2-1.0.so`, which is part of the Dota 2 libraries, looks for 
`symbol png_set_expand_gray_1_2_4_to_8 version PNG12_0`
as the error message states. 

A quick look into my Ubuntu 18.04 libraries showed, that the required `libpng12.so` is only a symlink to `libpng16.so`, which apparently does not have this symbol.

~As libpng12 is not available for Ubuntu 18.04, i downloaded the libpn12 package from Ubuntu 16, and compiled it myself. After adding the correct `libpng12.so` into the library folder of Dota (`game/bin/linuxsteamrt64/`), the game started without issues.~ `Moderator note: This should not be done, instead, if possible please identify where the ABI incompatible symlink came from, then remove the system-wide symlink.`

Edit:
This Issue https://github.com/ValveSoftware/Dota-2/issues/1641 mentions the Problem already.

**Comment by kisak-valve** [comment]
Hello @JackTemaki, libpng12.so and libpng16.so are ABI incompatible and should never be symlinked together. Additionally, libpng12.so is provided by the Steam runtime, but if there's a symlink from one to the other, then Steam sees the system variant as newer than the Steam runtime variant, and it gets preferred by default.

If you're able to determine what added the symlink to your system, that would be interesting to know.

**Comment by JackTemaki** [comment]
@kisak-valve  I do not remember doing the symlink myself, and the date is 17. March 2019... but i am not completely sure if this was not done by me.

I was not familiar with the runtime folder structure, so I did not see the local file. Of course, when deleting the symlink, Dota 2 starts.

Edit:
17. March was the date updating from 16.04 to 18.04... so either something added the link during the update, or i did it by hand at the same time for whatever reason.

**Comment by TTimo** [comment]
Please do not attempt @JackTemaki's workaround - you may get Dota 2 running out of luck, and cause a bunch of other problems in return.

We think the problem is that Dota 2 shouldn't be including these pango libraries in the first place.

Try the following workaround instead:

- Go to `~/.steam/steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64`

- Rename the `libpango*` files so they are out of the way:

```
timo@phoenix ~/.s/s/S/c/d/g/b/linuxsteamrt64> ls -1al libpango*
-rwxr-xr-x 1 timo timo 2832047 Aug 28  2019 libpango-1.0.so.off*
-rwxr-xr-x 1 timo timo 6955707 Aug 28  2019 libpangoft2-1.0.so.off*
```

- Run the library pinning again, in case those libraries are not present on your host (but really they should): `~/.steam/steam/ubuntu12_32/steam-runtime/setup.sh --force`

- On Debian and derivatives, create symlinks in `~/.steam/steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64` to your host version of the libraries. Note the host libraries are `libpango-1.0.so.1` and the Dota 2 version needs to be `libpango-1.0.so`.

- Check that Dota 2 works
(please report whether this works or not, with distro info and updated logs)

**Comment by gemakochi** [comment]
no luck for me.

![2020-03-19 23-36-07 ekran görüntüsü](https://user-images.githubusercontent.com/581848/77113620-38b21b80-6a3c-11ea-8bd7-477d701bf136.png)

[console.txt](https://github.com/ValveSoftware/Dota-2/files/4356865/console.txt)
[crash_20200319233543_1.zip](https://github.com/ValveSoftware/Dota-2/files/4356867/crash_20200319233543_1.zip)

**Comment by TTimo** [comment]
Looks like Dota 2 tries to do an explicit load - what happens if you try to symlink the two files from the `linuxsteamrt64` to your distribution's version of those files?

I cannot reproduce this on Arch either, the game starts fine without the need for symlinks to the host libraries for me (update: I know why Arch does not require the symlinks, that's because it comes with `libpango-1.0.so` in system libs in addition to `libpango-1.0.so.1` - Debian and co only have the latter).

**Comment by gemakochi** [comment]
at first game didn't launched then i run `~/.steam/steam/ubuntu12_32/steam-runtime/setup.sh --force`, it worked for once. i closed game and it's not working again. this is same situation as i thought it was fixed.

[console.txt](https://github.com/ValveSoftware/Dota-2/files/4360852/console.txt)
[crash_20200320194.zip](https://github.com/ValveSoftware/Dota-2/files/4360848/crash_20200320194.zip)

**Comment by FireCulex** [comment]
Ubuntu 20.04 I'm getting the same thing as gemakochi's youtube video. Game shows the logo, and then quits no explanation. This is a clean install out of the box. Tried tinkering over an hour but I couldn't figure it out what the problem is and I don't know how to analyze dmp files.

I suspect its intermittent, after attempting to launch the game 22 times, it actually loaded twice and crashed 20.

[crash.zip](https://github.com/ValveSoftware/Dota-2/files/4388671/crash.zip)

**Comment by smcv** [comment]
> (update: I know why Arch does not require the symlinks, that's because it comes with libpango-1.0.so in system libs in addition to libpango-1.0.so.1 - Debian and co only have the latter).

The version with just `.so` is the development symlink, intended to be used by developers to link executables with `-lpango-1.0`. The version with `.so.1` is the runtime symlink, intended to be used by programs at runtime. Your Arch system has both because Arch doesn't separate development library packages from runtime library packages. In Debian derivatives the development symlink is in the `-dev` package, and in Red Hat derivatives it's in the `-devel` package. Installing the `libpango1.0-dev` package on a Debian-derived system would make it behave like Arch in this respect.

If Dota wants to load a version of libpango that conforms to ABI version 1, it should be using `dlopen ("libpango.so.1")`, so that it will not get a really ancient version (ABI version 0) or a hypothetical future version (ABI version 2 or up).

**Comment by TTimo** [comment]
The workaround I described still applies.

It will take a little bit as I get setup with the Dota 2 source to get a fixed version pushed through the pipes to fix this.

It's quite possible that there are other crashes beyond the pango problem, which will need to be tracked as separate issues.

As another alternative, Dota 2 works great when executed within the container runtime configuration (without requiring libpango manipulations).

**Comment by qt1** [comment]
@TTimo 
Hi, can you please give more info about the container runtime configuration?
(docker?)
Thanks

**Comment by TTimo** [comment]
@qt1 set Dota 2 to use the 'Steam Linux Runtime' compatibility tool, like so: https://gyazo.com/a44a42c28df8eae9112a0128af9681bb

**Comment by qt1** [comment]
It is starting' king of, then fails.

...
RecordSteamInterfaceCreation (PID 185196): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
RecordSteamInterfaceCreation (PID 185196): SteamInput001 / 
in\win64\dota2.exe: ../src-wine/dlls/ntdll/unix/virtual.c:1243: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.
in\win64\dota2.exe: ../src-wine/dlls/ntdll/unix/virtual.c:1243: create_view: Assertion `!((UINT_PTR)base & page_mask)' failed.


---------------------------------------------------------
Encountered crash.
Wrote minidump to dota2_2021_0413_033254_1_crash.mdmp
---------------------------------------------------------

pid 185136 != 185135, skipping destruction (fork without exec?)
Game removed: AppID 570 "", ProcID 185196 
Game 570 created interface STEAMAPPLIST_INTERFACE_VERSION001 / 
...


and then it gets stuck until killall -9 dota2

**Comment by kisak-valve** [comment]
Hello @qt1, that reads like you've configured Steam to try to run the Windows Dota 2 client via Proton instead of the native Linux client inside of the Steam Linux Runtime container environment.

**Comment by qt1** [comment]
I see, so proton is the windows client. 
I actually tried several options, including the suggestions above linking the so files. Must have copied the trail with proton..

This is what happens when switching to steam linux runtime:

        Installing breakpad exception handler for appid(steam)/version(1618256785)
        [570]Non-Steam Controller Configs Enabled: 1
        Installing breakpad exception handler for appid(steam)/version(1618256785)
        [0413/042809.800281:ERROR:frame_sink_video_capturer_impl.cc(206)] Invalid resolutions constraints: 0x0 must not be greater than 0x0; and also within media::limits.
        Could not connect to X session manager: None of the authentication protocols specified are supported
        Could not connect to X session manager: None of the authentication protocols specified are supported
        Could not connect to X session manager: None of the authentication protocols specified are supported
        Could not connect to X session manager: None of the authentication protocols specified are supported
        [570]Non-Steam Controller Configs Enabled: 1
        Installing breakpad exception handler for appid(steam)/version(1618256785)



And when running dota2:

        If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
        Fossilize WARN: Referenced Pipeline layout bb687473e4599dc7, but it does not exist.
        This can be expected when replaying an archive from Steam.
        If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
        Fossilize WARN: Referenced Pipeline layout 8b944b8d585454b8, but it does not exist.
        This can be expected when replaying an archive from Steam.
        If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
        Fossilize WARN: Referenced Pipeline layout 9f991a11ef5855a9, but it does not exist.
        This can be expected when replaying an archive from Steam.
        If replaying just the application cache, make sure to replay together with the common cache, as application cache can depend on common cache.
        Fontconfig warning: "/srv/data1/files/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 148: Having multiple values in <test> isn't supported and may not work as expected
        Fontconfig warning: "/srv/data1/files/steamapps/common/dota 2 beta/game/core/panorama/fonts/conf.d/41-repl-os-win.conf", line 160: Having multiple values in <test> isn't supported and may not work as expected
        RecordSteamInterfaceCreation (PID 188226): SteamUser021 / 
        RecordSteamInterfaceCreation (PID 188226): SteamFriends017 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils010 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMaking009 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchGameSearch001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMakingServers002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUSERSTATS_INTERFACE_VERSION012 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPS_INTERFACE_VERSION008 / 
        RecordSteamInterfaceCreation (PID 188226): SteamNetworking006 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): SteamController007 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUGC_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPLIST_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSIC_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMINVENTORY_INTERFACE_V003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMVIDEO_INTERFACE_V002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamInput001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils009 / Utils
        RecordSteamInterfaceCreation (PID 188226): SteamNetworkingSocketsSerialized004 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUser020 / User
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / HTTP
        RecordSteamInterfaceCreation (PID 188226): SteamUser021 / 
        RecordSteamInterfaceCreation (PID 188226): SteamFriends017 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils010 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMaking009 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchGameSearch001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMakingServers002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUSERSTATS_INTERFACE_VERSION012 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPS_INTERFACE_VERSION008 / 
        RecordSteamInterfaceCreation (PID 188226): SteamNetworking006 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): SteamController007 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUGC_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPLIST_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSIC_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMINVENTORY_INTERFACE_V003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMVIDEO_INTERFACE_V002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamInput001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUser021 / 
        RecordSteamInterfaceCreation (PID 188226): SteamFriends017 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils010 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMaking009 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchGameSearch001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMakingServers002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUSERSTATS_INTERFACE_VERSION012 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPS_INTERFACE_VERSION008 / 
        RecordSteamInterfaceCreation (PID 188226): SteamNetworking006 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): SteamController007 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUGC_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPLIST_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSIC_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMINVENTORY_INTERFACE_V003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMVIDEO_INTERFACE_V002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamInput001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamAppDisableUpdate001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamGameCoordinator001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUser021 / User
        RecordSteamInterfaceCreation (PID 188226): SteamUser021 / 
        RecordSteamInterfaceCreation (PID 188226): SteamFriends017 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils010 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMaking009 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchGameSearch001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamMatchMakingServers002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUSERSTATS_INTERFACE_VERSION012 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPS_INTERFACE_VERSION008 / 
        RecordSteamInterfaceCreation (PID 188226): SteamNetworking006 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMREMOTESTORAGE_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMSCREENSHOTS_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / 
        RecordSteamInterfaceCreation (PID 188226): SteamController007 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMUGC_INTERFACE_VERSION014 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMAPPLIST_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSIC_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMMUSICREMOTE_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMHTMLSURFACE_INTERFACE_VERSION_005 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMINVENTORY_INTERFACE_V003 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMVIDEO_INTERFACE_V002 / 
        RecordSteamInterfaceCreation (PID 188226): STEAMPARENTALSETTINGS_INTERFACE_VERSION001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamInput001 / 
        RecordSteamInterfaceCreation (PID 188226): SteamUtils010 / 
        RecordSteamInterfaceCreation (PID 188226): SteamController007 / 
        RecordSteamInterfaceCreation (PID 188226): SteamInput001 / 
         failed to dlopen "libtensorflow.so" error=libtensorflow.so: cannot open shared object file: No such file or directory
        RecordSteamInterfaceCreation (PID 188226): STEAMHTTP_INTERFACE_VERSION003 / 

And now it looks like it is stuck. 
Maybe it is in some limbo graphic state?

Is there a way to reset the graphic mode?

It does not respond to `quit`.. or `killall dota2`
only `killall -9 dota2` works.

**Comment by Turmfalke2** [comment]
you can ignore the libtensorflow.so error, that one isn't fatal.

you can edit/reset your config in `~/.steam/steam/steamapps/common/dota 2 beta/game/dota/cfg`.
`video.txt` is likely the relevant one for you.

**Comment by qt1** [comment]
Thanks!
I'll try.

**Comment by JobeSound** [comment]
I had the "failed to dlopen..." error only when I had a controller connected. Both disconnecting the controller an the -nojoy launch option fixed the problem. The same thing occured in CSGO with the same fix

**Comment by atasoglou** [comment]
> Please do not attempt @JackTemaki's workaround - you may get Dota 2 running out of luck, and cause a bunch of other problems in return.
> 
> We think the problem is that Dota 2 shouldn't be including these pango libraries in the first place.
> 
> Try the following workaround instead:
> 
>     * Go to `~/.steam/steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64`
> 
>     * Rename the `libpango*` files so they are out of the way:
> 
> 
> ```
> timo@phoenix ~/.s/s/S/c/d/g/b/linuxsteamrt64> ls -1al libpango*
> -rwxr-xr-x 1 timo timo 2832047 Aug 28  2019 libpango-1.0.so.off*
> -rwxr-xr-x 1 timo timo 6955707 Aug 28  2019 libpangoft2-1.0.so.off*
> ```
> 
>     * Run the library pinning again, in case those libraries are not present on your host (but really they should): `~/.steam/steam/ubuntu12_32/steam-runtime/setup.sh --force`
> 
>     * On Debian and derivatives, create symlinks in `~/.steam/steam/SteamApps/common/dota 2 beta/game/bin/linuxsteamrt64` to your host version of the libraries. Note the host libraries are `libpango-1.0.so.1` and the Dota 2 version needs to be `libpango-1.0.so`.
> 
>     * Check that Dota 2 works
>       (please report whether this works or not, with distro info and updated logs)

This didn't work for me using arch-linux. I disabled Steam-Play as suggested [here](https://github.com/ValveSoftware/Dota-2/issues/2018#issuecomment-1026385240) and at least dota runs now.

**Comment by dmknght** [comment]
I'm having this issue after Dota 2 update to latest version (21 Jun). Disable remote play didn't help me fix the problem.
p/s: I think i misunderstood the "steam play" and "remote play". According to first result of google, Steam play is `a feature that allows you to run compatibility layers in the Linux version of the Steam client`. So basically it's switching from Linux native client to Windows client? If that's correct then it's not the actual "fix" IMO

**Comment by yepIwt** [comment]
Just checked. Same error after June 21st update

**Comment by MaxLuong** [comment]
Same thing with June 21st update.

I got it running by shutting down Steam and starting it from the command line with this extra option.

steam %U STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0

Found this solution from here:
https://forums.opensuse.org/t/after-steam-update-the-games-is-not-launching/125909/21

**Comment by dmknght** [comment]
Big thanks to @MaxLuong . On my side, i just need to run `steam %U` and the problem is fixed
![image](https://github.com/ValveSoftware/Dota-2/assets/29118926/1f540e82-f51a-4b9b-9d35-27678495253f)
P/s: The solution was mentioned here actually. Shoot out @gemakochi for the solution too https://github.com/ValveSoftware/Dota-2/issues/1705#issuecomment-599612664

**Comment by yepIwt** [comment]
> Big thanks to @MaxLuong . On my side, i just need to run `steam %U` and the problem is fixed ![image](https://user-images.githubusercontent.com/29118926/247391603-1f540e82-f51a-4b9b-9d35-27678495253f.png)

Thanks!!!!

**Comment by vkghc** [comment]
Hello, I'm running 6.8.9-arch1-2 .  

Dota 2 won't launch since yesterday with the same error messages as described above. I've tried running in XFCE4 with X, and in wayland with sway. Tried both the native and flatpak Steam apps. Same issue persists. 

Starting steam with `steam %U STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` does NOT fix the issue. 

I get the following messages every time when running either the above command or starting Dota 2 from the Steam UI.  Has anyone got an alternative solution to the issue?

```
/usr/share/themes/Adwaita-dark/gtk-2.0/main.rc:733: error: unexpected identifier 'direction', expected character '}'
/usr/share/themes/Adwaita-dark/gtk-2.0/hacks.rc:28: error: invalid string constant "normal_entry", expected valid string constant

Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element

Loaded libpangoft2-1.0.so, got (nil)
 failed to dlopen "libpangoft2-1.0.so" error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory

~/.local/share/Steam/steamapps/common/dota 2 beta/game/dota.sh: line 122: 15171 Bus error               (core dumped) ${STEAM_RUNTIME_PREFIX} ${GAME_DEBUGGER} "${GAMEROOT}"/${GAMEEXE} "$@"
```

**Comment by kisak-valve** [comment]
Hello @vkghc, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.

**Comment by vkghc** [comment]
Thank you for the helpful suggestion, @kisak-valve !

Downgrading the kernel to 6.8.4 seems to fix the issue. Dota 2 launches as expected from both flatpak and native Steam. 

Is the longer term solution to wait for kernel 6.9 where the issue will apparently be fixed?

thanks!

**Comment by smcv** [comment]
> Starting steam with `steam %U STEAM_RUNTIME_PREFER_HOST_LIBRARIES=0` does NOT fix the issue.

There are at least two separate reasons why that option won't do what you might imagine it does: that's the wrong way to set environment variables, and even if set as an environment variable [it has been ignored since 2020](https://github.com/ValveSoftware/steam-runtime/commit/7f8e8411236551cdcebd1cfd09de3758c2c8015a) because it broke too many things. So if that appeared to have worked for someone at any time in the last few years, it must have been coincidence.

**Comment by kuramayouko** [comment]
> Hello @vkghc, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.

Thank You. I had the same problem 3 days ago on Fedora i would never guessed that the kernel 6.8.9 was the reason that Dota was crashing on menu

**Comment by czhunor** [comment]
> > Hello @vkghc, can you check if https://gitlab.freedesktop.org/drm/amd/-/issues/3343 is relevant to your system? A quick test would be to reboot into an older kernel and see how the game behaves.
> 
> Thank You. I had the same problem 3 days ago on Fedora i would never guessed that the kernel 6.8.9 was the reason that Dota was crashing on menu

Downgrading to 6.8.4 on Archlinux worked for me also.

**Comment by rettetdemdativ** [comment]
I'm on 6.9.8 and have the same issue.

**Comment by pgibler** [comment]
I'm running into this issue on a fresh install of Ubutu 24.04 using kernel version 6.11.0 with libpango installed already. I installed steam using snap, flatpak, and the apt package manager, and tried loading Dota 2 in all of them, with the same error about libpango.

```
26(0.772199):  CONTENT              "/home/gibler/.steam/debian-installation/steamapps/common/dota 2 beta/content/core/" 
25(0.772199):  CONTENT              "/home/gibler/.steam/debian-installation/steamapps/common/dota 2 beta/content/dota/" 
24(0.772198):  ADDONS               "/home/gibler/.steam/debian-installation/steamapps/common/dota 2 beta/game/dota_addons/" 
23(0.772187):  Path ID:             File Path:
22(0.772184):  ---------------
21(0.363691):   failed to dlopen libpangoft2-1.0.so error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory
20(0.363438):  Disabling graphics pipeline libraries for shader 'error.vfx_vs' because it has unsupported descriptor types [ STORAGE_BUFFER ].  Move them to a static descriptor set.
19(0.358603):  Failed to save video settings config to 'cfg/video.txt'
18(0.282275):  Unable to open Vulkan pipeline cache shadercache/vulkan/shaders.cache file - might not exist yet.
17(0.190077):  Failed to save video settings config to 'cfg/video.txt'
16(0.189479):  (565): ADD setting.version = 1
15(0.189478):  (565): ADD setting.gpu_level = 3
14(0.189477):  (565): ADD setting.defaultresheight = 1200
13(0.189476):  (565): ADD setting.defaultres = 1900
12(0.189474):  Video Card dxsupport (10de : 2684)
11(0.189222):  (14): Setting setting.gpu_mem_level to 2
10(0.189117):  (9): Setting setting.mem_level to 2
9(0.189004):  (18): Setting setting.cpu_level to 2
8(0.139264):  USRLOCAL path using Steam profile data folder:
/home/gibler/.steam/debian-installation/userdata/27008059/570/local
7(0.089702):  Visibility enabled.
6(0.049021):  CSteam3Client::Activate succeeded.  SteamID is [U:1:27008059] (76561197987273787), AppID is 570
5(0.048834):  ResetBreakpadAppId: Setting non standard break pad app id: 373300
4(0.048832):  ResetBreakpadAppId: Universe is 1 (k_EUniversePublic)
3(0.048818):  SteamAPI_Init succeeded.  SteamID is [U:1:27008059] (76561197987273787), AppID is 570
2(0.040502):  InitSteamLogin_Internal: Initializing breakpad.
1(0.040491):  Steam AppId(570), BreakpadId(373300)
```

I'd very much appreciate some help on resolving this.

Ubuntu 24.04 even advertises Dota 2 during it's installation as a game that works out of the box, which it does not for me and apparently others. Please help get this resolved. I enjoy playing Dota 2 with my friends and now I can't :(

**Comment by smcv** [comment]
> `failed to dlopen "libpangoft2-1.0.so" error=libpangoft2-1.0.so: cannot open shared object file: No such file or directory`

I don't think this specific error message is necessarily a real problem, or related to whatever real problem various Dota 2 players are encountering. Perhaps ideally Dota 2 wouldn't attempt to load this module if it doesn't need it, or wouldn't log the error message, because it's distracting and misleads people into thinking this is the root cause for a crash, but I see this error message every time the game is launched - even on systems where Dota 2 is working fine, such as a Steam Deck.

@pgibler, if you do not see the symptom that the original reporter of this issue described:

> Get black screen with window "Unable to load libpangoft2-1.0.so, your game install may be corrupted or you may system conflict"

then whatever crash you are seeing is probably something different, and it might be better to report it separately with as much information as you can provide.

(I am not a Dota 2 developer and cannot help you to solve this bug myself.)

**Comment by k-bala-vignesh** [comment]
This worked for me
Set the launch options to:

`VK_INSTANCE_LAYERS=VK_LAYER_MESA_anti_lag MESA_VK_ANTI_LAG=1 RADV_PERFTEST=aco,gpl DXVK_SHADER_CACHE_PATH="$HOME/.cache/dxvk" MESA_VK_WSI_PRESENT_MODE=FIFO SDL_AUDIODRIVER=alsa PIPEWIRE_LATENCY=0 gamemoderun %command% -vulkan -prewarm -novid -high -map dota -console -processheap -disable_affinity_preferences -threads 4 -dota_embers 0 -r_shadowquality 0 -r_particles 0 -r_rootlod 1 -fps_max 120 -nojoy`
