### ISSUE TITLE
Dota 2 never shuts down correctly

### ISSUE THREAD

**Issue by broconut123** [ValveSoftware/Dota-2#2006]
#### Your system information

* System information from steam: https://gist.github.com/broconut123/cd64c365f985ddc1a112ae308c5c59e6
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes, using Nvidia Driver Version: 495.46
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
I've been using Dota 2 for linux for a few months and the game never closes when quitting game. I always have to kill the dota 2 process manually. It's the same issue with both KDE and Gnome on Arch Linux.

**Comment by wildcard-f8** [comment]
Manjaro Gnome here, also happening with 495. I went down to 470 and it acts normally when quitting. Also FPS is a little better.

**Comment by amardhruva** [comment]
Hmm Ubuntu 21.10 here with 495 drivers. Seems to be happening even after OS reinstall.

**Comment by Mario156090** [comment]
Me too with Arch Linux.

**Comment by willianwt** [comment]
same here, this started after this battle pass update.
linux mint 20.1 with 495 nvidia drivers

**Comment by lawli3t** [comment]
+1 on Arch Linux with Nvidia 495 drivers

**Comment by headlesscyborg** [comment]
It's probably the 495.44 driver. Not only if fails to exist properly but also performance is very bad if certain effects and particles appear on the screen - https://forums.developer.nvidia.com/t/performance-issues-in-dota-2-on-495-44/195012

**Comment by Lorkes** [comment]
Same here on Arch Linux, driver 495

**Comment by edmael** [comment]
+1, there's another old thread with the same issue, but I think this one is related to 495 nvidia driver.

**Comment by mewt666** [comment]
Can confirm, happens on every run of the game, game crashes on quitting. Switching to the steam client and closing game from there appears to kill all processes and Dota 2 can be started again. 

Nvidia 495.46 
Arch Linux

**Comment by mfed3** [comment]
I have the same problem. Reproducible crash every time when quitting. Alt tab to Steam to force close has to be done to kill the process. 

Operating System: Arch Linux
KDE Plasma Version: 5.23.5
KDE Frameworks Version: 5.89.0
Qt Version: 5.15.2
Kernel Version: 5.15.13-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 62.8 GiB of RAM
Graphics Processor: NVIDIA GeForce GTX 1070/PCIe/SSE2
NVIDIA Package: 495.46-7

**Comment by xelnagamex** [comment]
Same here on Arch Linux x86_64, nvidia 495.46-6

**Comment by buncis** [comment]
Ubuntu 20.04 

using NVIDIA Driver Version : 470.86 fixed the problem for me

**Comment by voidbreath** [comment]
Same here, crash on every close. 
Arch Linux
Xfce4 
nvidia 495.46-10

**Comment by Coo-ops** [comment]
Fix this.

Fedora 34

**Comment by Mario156090** [comment]
> Fix this.
> 
> Fedora 34

nvidia new drivers with?

**Comment by wildcard-f8** [comment]
Tested out the 510 Nvidia driver, still very poor performance. Main menu is in the 20 FPS range, but when I go to settings or other sections like the Watch tab, it shoots up to 120. In-game FPS is worse at around the low teens. But quitting the game is fixed.

Still have to use the Nvidia 470 driver for normal performance.

**Comment by 13k** [comment]
Game was still crashing on every exit for years now, but now it won't even quit, I have to manually kill the process every time.
