### ISSUE TITLE
[Linux] Can't select audio device + initially no sound

### ISSUE THREAD

**Issue by phoerious** [ValveSoftware/Dota-2#253]
First of all, I think this is related to issue #111. But since that one is closed already but the issue is not fixed with the latest beta update, I open a new one.

When I go to my audio settings, there is no default device selected, i.e. the field is empty. When I click on it, I get a dropdown with the Pulseaudio default device and a list of my audio cards and headsets. Selecting default doesn't do anything, the field stays empty. Selecting any other option freezes the game and I have to kill it with killall -9 dota2.

There is also no sound when I start the game. To get any sound I first have to plug in my headset once (or if it is plugged in, unplug and plug it back in). After that sound works normally, but the selection dropdown is still empty.

**Comment by gdrewb-valve** [comment]
I was able to repro issues with the initial state of the audio device dropdown, a fix for that will go out in the next update.  I wasn't able to repro a hang but I found https://forums.libsdl.org/viewtopic.php?t=9457&sid=ac1ba90da23d6295b4a5fa4dff28bae7 so it's possible the hang you're seeing is in SDL.  I did find an issue where Reborn was resetting audio state much too often when clicking through audio settings and that may have made the hang problem worse for you, that will also be fixed in the next update.

I wasn't able to repro the no-initial-sound problem.  After the next update comes out we'll see where things are at.

**Comment by phoerious** [comment]
Thanks. The issue with having no audio after starting Dota is 100% reproducible here. I always have to unplug my headset, then sound is working. When I then plug it back in, it keeps working until I restart Dota.
Are there maybe any logs that could be of interest for you? E.g. pulseaudio -vvvv?

**Comment by phoerious** [comment]
I noticed that I also have no sound in some other SDL-based games, like The Witcher II and ARK. Unfortunately, unplugging the headset doesn't fix it for those games, but maybe the issue is the same.
I tried to run the games directly from the command line, but wasn't able to get any useful debug output. Is there a way to get debug output in Dota2 Reborn? It would probably help me solving this issue. I guess it has something to do with Pulseaudio 6.0 because I was able to play The Witcher II a while ago with sound.

**Comment by gdrewb-valve** [comment]
Did the 7/28 update fix the initial dropdown value?  Did it have any effect on the no-initial-sound issue?  From your post about other games also having problems it likely won't.

Unfortunately there's no special debug output for sound in Reborn, plus we use SDL so the underlying audio implementation is hidden from Reborn.

**Comment by phoerious** [comment]
Yes, it fixed the initial dropdown value, but no, the sound issue is not gone. In fact, it got worse.
After I started Reborn for the first time after performing the update, the game hung when opening the Audio tab in the settings until I plugged in the headset. After I did that, everything acted normally and the device selection also wasn't empty anymore.

But now at every consecutive startup, Reborn hangs at the black loading screen with the red Dota2 logo until I plug in the headset.

So my guess is that Reborn (or SDL) is somehow waiting for an audio device or a device list which doesn't appear until I trigger some sort of refresh by plugging in the headset.

**Comment by gdrewb-valve** [comment]
We'll have to try and set up a matching system at some point to get into deeper details.

**Comment by phoerious** [comment]
Chakra Linux (Arch-based)
Pulseaudio 6.0
KDE 4.14.7

I'll get in touch with the distro maintainers, maybe they have some ideas.

I also had a sound issue with Kodi a while ago which led to a fix in Pulseaudio (that obviously hasn't made it to my distro yet). I don't know if Kodi (Helix) uses SDL for audio, but there is some SDL code in that application. I never worked with Pulseaudio at code level, so I can't really judge if this is of any value for you, but maybe this thread might be interesting for the whole topic: http://forum.kodi.tv/showthread.php?tid=228988

**Comment by phoerious** [comment]
Hmm. I tried killing pulseaudio and then restarting it with very verbose debug logging (pulseaudio -vvvv). Unfortunately, then Reborn doesn't start at all anymore. It just hangs at the loading screen, no matter how often I remove and plug my headset back in.
Still, here's the gathered log file in case it's of any use: http://pastebin.com/9Js0BaLd

**Comment by phoerious** [comment]
Because I didn't know any other solution I tried a clean live environment from DVD and audio seemed to work properly in all mentioned applications. Therefore I reinstalled my system partition with a fresh and clean ChakraOS and those issues are gone. I have no idea why, but I already suspected that a reinstallation would help. I have sound in all of those SDL games, I have sound in Kodi and Reborn doesn't hang anymore at startup or when selecting another sound device.

After not having to reinstall my OS for several years, I hope it'll stay functional now for the next years to come. :-)

**Comment by gdrewb-valve** [comment]
Should this stay open then or should I close it?

**Comment by phoerious** [comment]
Since I doubt that we'd be able to debug the actual problem, I think this can be closed.

**Comment by gdrewb-valve** [comment]
OK, thanks.  We'll reopen if you get more info on what the issue might be.
