### ISSUE TITLE
Pugna's Ulti Crash

### ISSUE THREAD

**Issue by christian102094** [ValveSoftware/Dota-2#2581]
#### Your system information

* System information from steam (`Steam` -> `Help` -> `System Information`) in a [gist](https://gist.github.com/): 
* Have you checked for system updates?: Yes
* Are you using the latest stable video driver available for your system? Yes
* Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
Describe what you _expected_ should happen and what _did_ happen. Please link any large pastes as a [Github Gist](https://gist.github.com/).

When I play Pugna and ulti any heroe, most of times the game crashes. I've been able to solve it (kind of randomnly) plugin out and in my USB-c dock where I connect Logiitech G502 Mouse and Logitech G915 keyboard. This crash happens to me a lot, and always when draining with Pugna's ulti.

[Link to Crash Info in MacOS](https://gist.github.com/christian102094/d33e7df9c3f461474759817b6675a716)

#### Steps for reproducing this issue:

1. Enter ranked game or hero's demo
2. Choose Pugna
3. Ulti any heroe with Pugna's drain
4. Game crashes

**Comment by christian102094** [comment]
I just figured that this has to do with the item "Golden Eye of Ix'yxa", which modifies ulti. When I take it off the game doesn't crash anymore.

**Comment by asaadmahmood** [comment]
The same exact thing happens to me.

**Comment by bdunn313** [comment]
I cannot confirm if it's related to the cosmetic mentioned by @christian102094 above, but I can confirm that my mac mini M1 crashes regularly when I'm in a game with Pugna. Anecdotally, it does seem to be when someone is playing pugna with a cosmetic that changes his ult, but I'm not certain that this is the case.

Here's my system info if helpful:
```
Computer Information:
Manufacturer: Apple
Model: Macmini9,1
Form Factor: Desktop
No Touch Input Detected
Processor Information:
CPU Vendor: VirtualApple
CPU Brand: Apple M1
CPU Family: 0x6
CPU Model: 0xc
CPU Stepping: 0x0
CPU Type: 0x0
Speed: 2400 MHz
8 logical processors
8 physical processors
Hyper-threading: Unsupported
FCMOV: Unsupported
SSE2: Supported
SSE3: Supported
SSSE3: Supported
SSE4a: Unsupported
SSE41: Supported
SSE42: Supported
AES: Supported
AVX: Unsupported
AVX2: Unsupported
AVX512F: Unsupported
AVX512PF: Unsupported
AVX512ER: Unsupported
AVX512CD: Unsupported
AVX512VNNI: Unsupported
SHA: Unsupported
CMPXCHG16B: Supported
LAHF/SAHF: Supported
PrefetchW: Unsupported
Operating System Version:
MacOS 12.3.0 (64 bit)
Video Card:
Driver: Apple M1
Driver Version: 190.17.3
OpenGL Version: 4.1
Desktop Color Depth: 32 bits per pixel
Monitor Refresh Rate: 60 Hz
VendorID: 0x106b
DeviceID: 0x0
Revision Not Detected
Number of Monitors: 1
Number of Logical Video Cards: 1
Primary Display Resolution: 2560 x 1440
Desktop Resolution: 2560 x 1440
Primary Display Size: 23.70" x 13.31" (27.17" diag), 60.2cm x 33.8cm (69.0cm diag)
Primary VRAM: 8192 MB
Memory:
RAM: 8192 Mb
VR Hardware:
VR Headset: None detected
Miscellaneous:
UI Language: English
Media Type: DVD
Total Hard Disk Space Available: 233752 MB
Largest Free Hard Disk Block: 17064 MB
Storage:
Number of SSDs: 0
Number of HDDs: 0
Number of removable drives: 0

```

**Comment by ivandjuricic** [comment]
+1 on this on Macbook Pro M1 Max
Played today as Mirana and suspected it was Pugna's ult but it wasn't happening on every cast so I couldn't be sure

Edit: Just checked Pugna had Eye of Ix'yxa item on him
Edit 2: It happens even on spectating match

**Comment by christian102094** [comment]
At least for me, this is solved. I did nothing special, just wait a couple of weeks without the cosmetic and try again.

**Comment by bdunn313** [comment]
This appears to be solved for me too; haven't seen the bug in some time.

**Comment by christian102094** [comment]
I will close this since the error seems to be solved. Thanks!

**Comment by nomadx** [comment]
it appears again on mac on june 39th latest patch

**Comment by koshyviv** [comment]
Im still facing this issue, its a pugna on the opposite team too - is there anything i can do other than just abandon?
