### ISSUE TITLE
[macOS] FPS drops and statters appear during the game

### ISSUE THREAD

**Issue by ove2xrate** [ValveSoftware/Dota-2#2653]
#### Your system information

System information from steam in a gist: https://gist.github.com/ove2xrate/5b541ddd754c72adcf4846fc9340e170
Have you checked for system updates?: Yes
Are you using the latest stable video driver available for your system? Yes
Have you verified the game files?: Yes

#### Please describe your issue in as much detail as possible:
During the game, FPS drops and stutters appear. At the beginning of the game FPS is around 200+ but towards the end of the game it drops to 40-60. Only restarting the game together with restarting Steam helps to solve the problem. After these actions FPS return to 200+ but during the time again falls. 

This problem was in the summer-autumn 2023 but then went away by itself. And now a week ago, the problem reappeared. 

#### Steps for reproducing this issue:
1. Start Dota 2
2. Find game
3. Just start playing

**Comment by babebbu** [comment]
I would like to confirm that this issue is present on macOS. I also tried reinstalling the game client but it doesn't resolve.

Here is my environment
CPU: Apple M1 Max, 10-core CPU, 32-core GPU
Memory: 32 GB
OS: macOS Sonoma 14.4

The step to reproduce is similar to what the author described.
1. Start Dota 2
2. Find a match
3. Plays for a while until FPS lagged (10 minutes+, maybe 25-30 minutes, I pretty sure the stutters approach during a long match)
4. Monitor the Dota 2 app memory from macOS's Activity Monitor (Found ~5GB memory usage)
5. Quit the game
6. Logout from Steam
7. Re-login Steam
8. Re-open Dota 2
9. Re-connect the match
10. Now the problem is resolved.

Here is more info for debugging.
I tried to capture the memory usage of the Dota 2 client, and in my machine, I found Dota 2 utilized up to 5 GB of RAM and mostly would not exceed 5Gb, but previously it utilized around 16 GB of RAM.

My first occurrence of this issue was around the implementation of Ancient's dragon cosmetic.

**Comment by ove2xrate** [comment]
It looks like the FPS issue has been resolved in patch 7.35d.

**Comment by ove2xrate** [comment]
@babebbu Hi! Are you still having FPS drops? I reinstalled Steam and Dota right before the 7.35d update came out. Maybe it wasn't the update that helped, but reinstalling Steam.

**Comment by tagirqa** [comment]
> @babebbu Hi! Are you still having FPS drops? I reinstalled Steam and Dota right before the 7.35d update came out. Maybe it wasn't the update that helped, but reinstalling Steam.

I encountered the same problem, but the patch did not help. I'll try to reinstall Steam and write about the result later.

setup: MacBook Pro 14 M1 Pro


update: I tried reinstall steam, not worked for me. Dota 2 client didn't reinstall

**Comment by babebbu** [comment]
> > @babebbu Hi! Are you still having FPS drops? I reinstalled Steam and Dota right before the 7.35d update came out. Maybe it wasn't the update that helped, but reinstalling Steam.
> 
> I encountered the same problem, but the patch did not help. I'll try to reinstall Steam and write about the result later.
> 
> setup: MacBook Pro 14 M1 Pro
> 
> update: I tried reinstall steam, not worked for me. Dota 2 client didn't reinstall

Hi all, I tried both reinstalling Steam and reinstalling Dota 2 client, but None of it solved. I'm still encountering FPS drop.

**Comment by tagirqa** [comment]
My FPS started dropping after updating the OS to Sonoma 14.4.1.

**Comment by babebbu** [comment]
> System information from steam in a gist: https://gist.github.com/ove2xrate/5b541ddd754c72adcf4846fc9340e170 Have 

@ove2xrate encountered the FPS drop with MacOS 14.3.0, I'm not sure whether the different minor version of macOS will be the factor of this issue.

I encountered with macOS 14.4.0 and 14.4.1.

**Comment by ove2xrate** [comment]
> Replying to https://github.com/ValveSoftware/Dota-2/issues/2653#issuecomment-2033887758

I'm so sorry. On macOS 14.4.1 now, I no longer have the FPS problem. 
If reinstalling Dota and Steam didn't help, then I don't know what's causing the problem 😞

**Comment by robert-b-payne** [comment]
UPDATE: I reinstalled Steam and Dota and it resolved the issue.

I'm getting this issue with 7.35d using M1 Pro 16 GB. The performance gradually degrades due to CPU bottlenecking. In Activity Monitor, I can see the CPU utilization decrease over time. At first it's at around 350% and then it drops to about 150% after an hour. This is not thermal throttling, the temps are fine.

The issue is 100% reproducible for me by simply watching replays or live matches. The performance starts at around 100 fps and then gradually lowers into the 30s over about an hour. The performance is still degraded when starting new games/replays and even after restarting Dota. Only restarting Steam fixes it.

Edit: This with Sonoma 14.4.1 (latest). I have verified the game files.

**Comment by SmolikD** [comment]
Same issue. 
Sonoma 14.6.1 
M1 pro 14
Reinstalling Dota and Steam haven't helped.

**Comment by Letni1** [comment]
Had the same issue. What helped is downloading https://app-cleaner.com/. Uninstalling dota. Uninstalling steam using app-cleaner. Reinstall everything. Works perfectly.
