### ISSUE TITLE
NVidia 535.x VK_ERROR_INITIALIZATION_FAILED on Debian

### ISSUE THREAD

**Issue by davidsl118** [ValveSoftware/Dota-2#2787]
Dota failing to launch after the most recent update (Major update with compendium)

![DotaVulkanIssue](https://github.com/user-attachments/assets/1ec4ff7c-d464-4539-8a67-b3c4b7991457)

**Comment by kisak-valve** [comment]
Hello @davidsl118, please copy the contents of Steam Runtime Diagnostics from Steam (`Steam` -> `Help` -> `Steam Runtime Diagnostics`) and put it in a [gist](https://gist.github.com/), then include a link to the gist in this issue report.

**Comment by davidsl118** [comment]
[Diagnostic gist](https://gist.github.com/davidsl118/ddd4448f56ac841df91b75ff187487ec)

**Comment by kagmole** [comment]
Same issue here on Debian Unstable.
It looks like it's trying to start on the integrated graphics and not the discrete graphic card.

**Comment by TormenTeDx** [comment]
Same here... Debian (bookworm), can't start the game since the ringmaster update...

**Comment by pavel-garmatyuk** [comment]
Similar problem, after updates there is no initialization of Vulcan, then it crashes with an error
![2024-08-23_16-18](https://github.com/user-attachments/assets/739b9789-6ea3-402e-b12d-d1b8edc522cf)

**Comment by TormenTeDx** [comment]
any workaround for this?

**Comment by kagmole** [comment]
I tried some solutions like `DRI_PRIME=1 %command%` or using Proton but no chance.
Looks like it's not working right now with Proton as well : https://www.protondb.com/app/570#EtQd9pA3uB

**Comment by TormenTeDx** [comment]
I tried with proton too, I have the same problem. It opens for like 5-10 seconds and then closes

**Comment by TTimo** [comment]
There was a problem earlier this week which could cause a system crash running out of descriptors shortly after startup. This has been fixed now, and OP's report is a different issue.

If you are not crashing on startup with a `Failed to initialize Vulkan` error, please consider opening a separate issue.

@davidsl118 can you go through the following steps to help diagnosing this:

- Set a launch option of `-consolelog $HOME/.steam/steam/logs/dota2.log` on Dota 2, e.g.
![30ed3284236a574342815425e3191dd0](https://github.com/user-attachments/assets/81fe121c-e839-42b6-8715-f202c4916985)
- Attempt to launch to reproduce the Vulkan init error again
- Send in your logs, which you can grab by running `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs`

**Comment by kagmole** [comment]
I ain't davids118 but here goes my own logs:
```
08/31 09:33:20 [RenderSystem] Loaded video settings config from 'cfg/video.txt'
08/31 09:33:20 [RenderSystem] vkCreateDevice failed with error VK_ERROR_INITIALIZATION_FAILED, unable to create Vulkan device.
```

**Comment by TormenTeDx** [comment]
Same here
`[logs]$ cat dota2.log`
`08/31 12:14:08 [RenderSystem] Loaded video settings config from 'cfg/video.txt'
08/31 12:14:08 [RenderSystem] vkCreateDevice failed with error VK_ERROR_INITIALIZATION_FAILED, unable to create Vulkan device.`

**Comment by kagmole** [comment]
Tried to remove the file `cfg/video.txt` and launch (bad config maybe?) but it still doesn't work.

**Comment by TTimo** [comment]
Thanks but I would prefer to look at the entire set of logs, not just the error line.

**Comment by TormenTeDx** [comment]
Here I zipped all logs.
[steam-logs.tar.gz](https://github.com/user-attachments/files/16825016/steam-logs.tar.gz)

**Comment by kagmole** [comment]
Maybe what you wanted was the output and error stream?
This is what I got:
```bash
$ ./dota.sh -consolelog /tmp/dota2.log > /tmp/dota2.out 2> /tmp/dota2.err
```
Log file:
```
08/31 16:25:39 [RenderSystem] Loaded video settings config from 'cfg/video.txt'
08/31 16:25:39 [RenderSystem] vkCreateDevice failed with error VK_ERROR_INITIALIZATION_FAILED, unable to create Vulkan device.
```
Output file:
```
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libengine2.so, got 0x5585e2ed4310
Loaded libSDL3.so.0, got 0x5585e2ffbb30
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libtier0.so, got 0x5585e2eb3030
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libfilesystem_stdio.so, got 0x5585e304d2d0
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libinputsystem.so, got 0x5585e305f990
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/liblocalize.so, got 0x5585e30c0aa0
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/librendersystemvulkan.so, got 0x5585e30b30b0
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libresourcesystem.so, got 0x5585e30cbd70
Loaded /home/kagmole/.steam/debian-installation/steamapps/common/dota 2 beta/game/bin/linuxsteamrt64/libschemasystem.so, got 0x5585e30ac890
```
Error file:
```
Using breakpad crash handler
[S_API] SteamAPI_Init(): Loaded '/home/kagmole/.steam/debian-installation/linux64/steamclient.so' OK.
Setting breakpad minidump AppID = 570
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
08/31 16:22:14 minidumps folder is set to /tmp/dumps
08/31 16:22:14 Init: Installing breakpad exception handler for appid(570)/version(9152686)/tid(4406)
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
SteamInternal_SetMinidumpSteamID:  Caching Steam ID:  76561198023953873 [API loaded yes]
SteamInternal_SetMinidumpSteamID:  Setting Steam ID:  76561198023953873
Setting breakpad minidump AppID = 373300
```

**Comment by TormenTeDx** [comment]
@kagmole You should just run `tar -zcvf ~/Desktop/steam-logs.tar.gz ~/.steam/steam/logs` to grab all the logs

**Comment by kagmole** [comment]
And here's mine. Removed all files from `logs` then did a Steam launch and Dota 2 launch.
[steam-logs.tar.gz](https://github.com/user-attachments/files/16825037/steam-logs.tar.gz)

**Comment by kagmole** [comment]
Tried to disable the iGPU (dGPU only) in the UEFI settings but no chance. :)

**Comment by davidsl118** [comment]
@TTimo Here are the compressed logs. 
[steam-logs.tar.gz](https://github.com/user-attachments/files/16833058/steam-logs.tar.gz)

**Comment by TTimo** [comment]
Thanks @davidsl118, I appreciate your patience. The logs didn't reveal anything unfortunately.

It looks like you are on an Optimus laptop, so let's try a few things:

- Try to run vkcube in the sniper runtime and validate that it initializes over the eGPU (your nvidia card):
`__NV_PRIME_RENDER_OFFLOAD=1 ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper -- vkcube`

On my Optimus system this reports `Selected GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU, type: DiscreteGpu` indicating it picked the eGPU over the iGPU.

If you don't specify the `__NV_PRIME_RENDER_OFFLOAD=1` I expect it'll report your software vulkan backend instead (llvmpipe).

- If this works, you can try to launch dota directly from the terminal like this (while the steam client is running):

```
timo@eta-carinae ~/.s/s/s/c/dota 2 beta> cd ~/.steam/steam/steamapps/common/dota\ 2\ beta/game/
timo@eta-carinae ~/.s/s/s/c/d/game> __NV_PRIME_RENDER_OFFLOAD=1 ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper -- ./dota.sh
```

You can find more information about Optimus at https://wiki.debian.org/NVIDIA%20Optimus

**Comment by kagmole** [comment]
The Steam Linux runtime folder may be here for Debian, if you used the Steam installer from the Debian repository:

```
~/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper
```

**Comment by TormenTeDx** [comment]
![image](https://github.com/user-attachments/assets/54ea3d6c-467f-497c-b00e-76a4e0ff426b)

I ran these `__NV_PRIME_RENDER_OFFLOAD=1 ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper -- vkcube` and with or without the argument I still get in both cases the same gpu nvidia rtx3080. and running dota through sniper gives the same vulkan error as it does via steam.

![image](https://github.com/user-attachments/assets/ad6e97d2-15d5-48df-af5b-362d8e1aa705)

Sadly it didn't help for me

**Comment by kagmole** [comment]
Same as @TormenTeDx, except graphic card is:

```
Selected GPU 1: NVIDIA GeForce RTX 4070 Laptop GPU, type: DiscreteGpu
```

**Comment by davidsl118** [comment]
Hi @TTimo. I get the vkcube rendered with or without the argument, and in both cases the same discrete GPU is selected. Since this was not what you expected, I did not test the next step.

**Comment by TTimo** [comment]
Ok .. so next thing to try, enabling verbose in the Vulkan loader:

`VK_LOADER_DEBUG=all __NV_PRIME_RENDER_OFFLOAD=1 ~/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper -- ./dota.sh 2>&1 | tee ~/verbose-loader.txt`

That will save out a log to `~/verbose-loader.txt` which you can attach and we'll see if it reveals anything.

**Comment by TormenTeDx** [comment]
Here you go: 
[verbose-loader.txt](https://github.com/user-attachments/files/16937205/verbose-loader.txt)

**Comment by TTimo** [comment]
I'll have to pour over the logs some more tomorrow, but can you also try setting `NODEVICE_SELECT=1` and capturing another? Just in case an issue in the llvmpipe layer is collapsing the whole init for some reason.

**Comment by TormenTeDx** [comment]
You mean like this? `NODEVICE_SELECT=1 VK_LOADER_DEBUG=all /home/ryszard/.steam/debian-installation/steamapps/common/SteamLinuxRuntime_sniper/run-in-sniper -- ./dota.sh 2>&1 | tee ~/verbose-loader-nodevice-select.txt`
Here, still getting vulkan error:
[verbose-loader-nodevice-select.txt](https://github.com/user-attachments/files/16940156/verbose-loader-nodevice-select.txt)

**Comment by TTimo** [comment]
Ok that makes the whole loading business cleaner, and at least removes that possibility of a problem.

At this point we're starting to suspect the combo of 535 drivers and recent NVidia hardware (3080 and up). We may be requesting extensions in the recent Dota2 update that the drivers are unhappy about. It'll take a few days but we'll add some options to test that out.

Corollary is that you should try with newer drivers, 550 or ideally 560 but it seems Debian is lagging behind, we've asked for those to be added in experimental.

**Comment by TormenTeDx** [comment]
cool, thanks. 535 are the newest one right now on stable debian afaik.

**Comment by kagmole** [comment]
Same for Debian Unstable. Version 535.183.06-1.
But a friend on Ubuntu doesn't have the problem with an older version, 535.183.01.
https://github.com/ValveSoftware/Dota-2/issues/2807#issuecomment-2323480228

**Comment by smcv** [comment]
> a friend on Ubuntu doesn't have the problem with an older version, 535.183.01

535.183.01 happens to still be available in the Debian 12 repositories (versioned `535.183.01-1~deb12u1`), so you could try downgrading to that and see whether it helps?

**Comment by TormenTeDx** [comment]
I have 535.183.01, so it won't help.
![image](https://github.com/user-attachments/assets/968a424b-0671-49cf-9baa-6ae7cebf85d9)

**Comment by kagmole** [comment]
I tried to downgrade but the DKMS build fails with Linux kernel 6.10.9-amd64.

**Comment by smcv** [comment]
> I have 535.183.01, so it won't help

If that's the case, then there must be some other factor in why you see this but @kagmole's friend does not. Everyone here seems to have mentioned dual-GPU (Nvidia + other), so perhaps that's part of it.

**Comment by TormenTeDx** [comment]
I have single gpu, 3080 rtx, its probably because of debian. I've heard it works on ubuntu fine

**Comment by kagmole** [comment]
I tried to disable the iGPU to only have one dGPU but no luck on this as well.

**Comment by smcv** [comment]
Do you have `libnvidia-rtcore` installed? If not, try installing that, at the same version as your Vulkan drivers?

As packaged in Debian, it's a Recommends (weak dependency, installed by default but possible to turn off), but there are indications that it should perhaps be a required dependency.

**Comment by smcv** [comment]
Or, more generally, if any of the dependencies of `nvidia-driver-full` are missing, try installing them, again with their version matching the parts of the driver that you already have installed.

**Comment by kagmole** [comment]
`libnvidia-rtcore` was indeed missing, no idea why. I installed it and now it works! Thanks a lot. :)
I will reinstall all recommended packages as well, just to be sure. I didn't disable the installation of recommended packages though.

**Comment by smcv** [comment]
> I didn't disable the installation of recommended packages though

Hmm, something must have gone wrong during installation or upgrade of your drivers: normally Recommends are selected for installation automatically, unless either (a) you explicitly turned them off (in which case you're accepting the risk that some things will not work), or (b) they were temporarily impossible to install for some reason.

**Comment by kagmole** [comment]
Must be option (b) since I'm on Unstable. I do admit I neglect to check on packages starting with `lib`.

**Comment by TormenTeDx** [comment]
I can't believe it, I installed libnvidia-rtcore and it works too. I think it wasn't installed since beggining and it just wasn't required for dota before... cause it basically stopped working after the ringmaster update

**Comment by smcv** [comment]
> I think it wasn't installed since beggining and it just wasn't required for dota before

Perhaps it's actually only required for games that use particular Vulkan features, and Dota started using those features recently?

**Comment by TTimo** [comment]
> Perhaps it's actually only required for games that use particular Vulkan features, and Dota started using those features recently?

Yep we do try to enable some raytracing extensions since recently.

**Comment by davidsl118** [comment]
After installing libnvidia-rtcore the game launches fine. Many thanks!

**Comment by smcv** [comment]
Reported as https://bugs.debian.org/1081314

**Comment by smcv** [comment]
> Reported as https://bugs.debian.org/1081314

This has been fixed in versions of nvidia-graphics-drivers that will hopefully be included in Debian 13.
