### ISSUE TITLE
[Linux]"In-game font is white box"problem

### ISSUE THREAD

**Issue by AegirVOD** [ValveSoftware/Dota-2#748]
First, I know is has an issue already, but the answer is only for ubuntu, I am using Debian 8.2.0.
Second, please, please, please, forgive my poor English, cuz I'm from China.
Aha, my laptop is Acer Aspire 5750, running Debian 8.2.0,  so here is my system information:
Processor Information:
    Vendor:  GenuineIntel
    CPU Family:  0x6
    CPU Model:  0x2a
    CPU Stepping:  0x7
    CPU Type:  0x0
    Speed:  2900 Mhz
    4 logical processors
    2 physical processors
    HyperThreading:  Supported
    FCMOV:  Supported
    SSE2:  Supported
    SSE3:  Supported
    SSSE3:  Supported
    SSE4a:  Unsupported
    SSE41:  Supported
    SSE42:  Supported

Network Information:
    Network Speed:  

Operating System Version:
    Debian GNU/Linux 8.2 (jessie) (64 bit)
    Kernel Name:  Linux
    Kernel Version:  3.16.0-4-amd64
    X Server Vendor:  The X.Org Foundation
    X Server Release:  11604000
    X Window Manager:  GNOME Shell
    Steam Runtime Version:  steam-runtime-release_2015-06-12

Video Card:
    Driver:  Intel Open Source Technology Center Mesa DRI Intel(R) Sandybridge Mobile x86/MMX/SSE2

```
Driver Version:  3.0 Mesa 10.3.2
OpenGL Version: 3.0
Desktop Color Depth: 24 bits per pixel
Monitor Refresh Rate: 59 Hz
VendorID:  0x8086
DeviceID:  0x116
Number of Monitors:  1
Number of Logical Video Cards:  1
Primary Display Resolution:  1366 x 768
Desktop Resolution: 1366 x 768
Primary Display Size: 13.58" x 7.64"  (15.55" diag)
                                        34.5cm x 19.4cm  (39.5cm diag)
Primary VRAM Not Detected
```

Sound card:
    Audio device: Intel CougarPoint HDMI

Memory:
    RAM:  3816 Mb

Miscellaneous:
    UI Language:  English
    LANG:  zh_CN.utf8
    Microphone:  Not set
    Total Hard Disk Space Available:  54316 Mb
    Largest Free Hard Disk Block:  17592 Mb

Installed software:

Recent Failure Reports:
==============System Information Over===============

I read the other 2 issues: #511  and #417 .
Well, now I know I have this problem because I have installed mesa10 instead of mesa11.
Let's upgrade it!
Then, I met problem.
First, the two issues both mentioned upgrading mesa, but they used ppa, but Debian cannot use ppa.
Then, I downloaded mesa-11.1.1.tar.xz, I .configure it, but it shows:
configure: error: Direct rendering requires libdrm >= 2.4.60
Well, guess I have to upgrade this libdrm stuff.
Here's the problem: I cannot find libdm 2.4.60 anywhere. I don't know how to upgrade libdrm to 2.4.60. Maybe this problem can be easily solved on Ubuntu, but I am using Debian. Does anyone know how to solve this problem on Debian? Really need some help. Thanks.

**Comment by danginsburg** [comment]
Instead of trying to build mesa-11.1.1, you could try mesa 10.5.8 which should fix this problem.  It may not require such a new version of libdrm.  Source can be downloaded here: ftp://ftp.freedesktop.org/pub/mesa/older-versions/10.x/10.5.8/

**Comment by Tele42** [comment]
@danginsburg, mesa 10.5.9 is the minimum version with proper rendering on Intel per https://github.com/ValveSoftware/Dota-2/issues/23#issuecomment-114913035, unless something has changed that I missed.

Edit: I missed the workaround was there, mesa 10.5.8 should work when the game is launched with `-gl_force_sm30`.

**Comment by danginsburg** [comment]
Under the hood it automatically does the equivalent of -gl_force_sm30 on mesa 10.5.8 to workaround the bug.  You are right though that 10.5.9 is preferred.  I just was trying to give @JiangMufan the oldest version that should still work so hopefully he can build it with his installed dependencies.

**Comment by AegirVOD** [comment]
Thanks, guys. I will try Mesa 10.5.9 first, because maybe i don't have to install -gl_force_sm30, if I can't install or it doesn't work, I'll try 10.5.8.Really thanks, both of you. @danginsburg  @Tele42

**Comment by AegirVOD** [comment]
Guys, new problem, I installed mesa 10.5.9(with a lot of difficulty), but, the System information in Steam still shows that I am in 10.3.2(the Graphic card driver version). How is that possible?

**Comment by Tele42** [comment]
Your 32 bit and 64 bit variants of mesa may not have matching versions. Dota 2 is 64 bit.

**Comment by JiangMufan** [comment]
How to do that On 2016-02-01 22:35 , Tele42 Wrote: @danginsburg, mesa 10.5.9 is the minimum version with proper rendering on Intel per #23 (comment), unless something has changed that I missed. — Reply to this email directly or view it on GitHub.

**Comment by AegirVOD** [comment]
@Tele42  But I didn't see any sign of x64 or x86 when I download the mesa package! Maybe I'll try to download 64-bit mesa and re-install it.

**Comment by gdrewb-valve** [comment]
This doesn't appear to be a Reborn issue, should this be closed?

**Comment by danginsburg** [comment]
Yes, @JiangMufan needs to upgrade to mesa 10.5.8.  Looks like he was have some trouble doing so, conversation can continue if needed but this can be closed.
